/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#81756d',
        'on-primary-fixed': '#29180a',
        'on-tertiary-fixed-variant': '#3c4b3a',
        'on-surface-variant': '#4f453e',
        'inverse-surface': '#31312d',
        'on-primary-fixed-variant': '#594231',
        'secondary-fixed-dim': '#ffb688',
        'primary-fixed-dim': '#e1c0aa',
        'tertiary-fixed': '#d7e7d1',
        'secondary-container': '#ffab74',
        secondary: '#8e4e1f',
        'inverse-on-surface': '#f3f0ea',
        'on-tertiary-fixed': '#111f11',
        background: '#fcf9f3',
        'on-secondary-fixed': '#311300',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#97a893',
        'surface-container-high': '#ebe8e2',
        'tertiary-container': '#2f3d2d',
        'outline-variant': '#d2c4bb',
        'on-primary': '#ffffff',
        'surface-container': '#f0eee8',
        error: '#ba1a1a',
        'surface-container-low': '#f6f3ed',
        'surface-container-highest': '#e5e2dc',
        'on-secondary': '#ffffff',
        tertiary: '#1a2719',
        'on-surface': '#1c1c18',
        'on-primary-container': '#bb9d88',
        'primary-fixed': '#fedcc5',
        'on-error': '#ffffff',
        surface: '#fcf9f3',
        'secondary-fixed': '#ffdbc7',
        'tertiary-fixed-dim': '#bbcbb6',
        'on-background': '#1c1c18',
        primary: '#322011',
        'on-secondary-container': '#783d0e',
        'inverse-primary': '#e1c0aa',
        'on-secondary-fixed-variant': '#703708',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dcdad4',
        'error-container': '#ffdad6',
        'surface-variant': '#e5e2dc',
        'on-tertiary': '#ffffff',
        'surface-bright': '#fcf9f3',
        'surface-tint': '#725947',
        'primary-container': '#4a3525',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.25rem',
        'gutter-mobile': '0.75rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
      boxShadow: {
        'warm-sm': '0 2px 6px -1px rgba(74, 53, 37, 0.03)',
        'warm-md': '0 10px 24px -4px rgba(74, 53, 37, 0.06), 0 2px 6px -1px rgba(74, 53, 37, 0.03)',
        'warm-lg': '0 20px 32px -8px rgba(74, 53, 37, 0.12), 0 4px 12px 0 rgba(74, 53, 37, 0.04)',
      },
    },
  },
  plugins: [],
};
